module.exports = {
  purge: ["./pages/**/*.tsx", "./components/**/*.tsx"],
  future: {
    removeDeprecatedGapUtilities: true,
  },
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
    },
    fontFamily: {
      display: ["Gilroy", "sans-serif"],
      body: ["Graphik", "sans-serif"],
    },
    height: {
      "0": "0",
      px: "1px",
      "1": "0.25rem",
      "2": "0.5rem",
      "3": "0.75rem",
      "4": "1rem",
      "5": "1.25rem",
      "6": "1.5rem",
      "8": "2rem",
      "10": "2.5rem",
      "12": "3rem",
      "16": "4rem",
      "20": "5rem",
      "24": "6rem",
      "32": "8rem",
      "40": "10rem",
      "48": "12rem",
      "56": "14rem",
      "64": "16rem",
      "128": "32rem",
      "1/4": "25%",
      "3/4": "75%",
    },
    maxHeight: {
      "1/4": "25%",
      "1/2": "50%",
      "3/4": "75%",
    },
    minHeight: {
      "1/4": "25%",
      "1/2": "50%",
      "3/4": "75%",
    },
  },
  variants: {
    textColor: ["responsive", "hover", "focus", "group-focus", "group-hover"],
    font: ["responsive", "hover", "focus", "group-focus", "group-hover"],
    width: ["responsive", "hover", "focus", "group-focus", "group-hover"],
    height: ["responsive", "hover", "focus", "group-focus", "group-hover"],
    maxWidth: ["responsive", "hover", "focus", "group-focus", "group-hover"],
    scale: ["responsive", "hover", "focus", "group-focus", "group-hover"],
  },
};
